# Generated by Django 5.1.3 on 2025-03-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_message_audio_alter_message_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='audio',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
    ]
