# Generated by Django 5.1.3 on 2025-03-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_message_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_type',
        ),
    ]
