# Generated by Django 5.1.4 on 2025-04-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_photo'),
        ('base', '0012_remove_message_file_type'),
    ]

    operations = [
    ]
