# Generated by Django 5.1.4 on 2025-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_merge_0011_photo_0012_remove_message_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='msg_type',
            field=models.CharField(choices=[('T', 'Tekst'), ('V', 'Głos')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
